FROM debian:buster
MAINTAINER Danny Edel <mail@danny-edel.de>

RUN echo deb-src http://deb.debian.org/debian buster main >> /etc/apt/sources.list

RUN apt-get update -y && apt-get install eatmydata -yV && eatmydata apt-get upgrade -yV

RUN eatmydata apt-get build-dep -y dspdfviewer

RUN eatmydata apt-get install -yV clang-5.0
