FROM debian:experimental
MAINTAINER Danny Edel <mail@danny-edel.de>

RUN echo deb-src http://deb.debian.org/debian sid main >> /etc/apt/sources.list

RUN apt-get update -y && apt-get install eatmydata -yV && eatmydata apt-get upgrade -yV

RUN apt-get build-dep -y dspdfviewer

RUN apt-get install -yV clang-6.0

RUN apt-get install -yV g++-8 -t experimental
