Document: dspdfviewer
Title: Debian dspdfviewer Manual
Author: <insert document author here>
Abstract: This manual describes what dspdfviewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dspdfviewer/dspdfviewer.sgml.gz

Format: postscript
Files: /usr/share/doc/dspdfviewer/dspdfviewer.ps.gz

Format: text
Files: /usr/share/doc/dspdfviewer/dspdfviewer.text.gz

Format: HTML
Index: /usr/share/doc/dspdfviewer/html/index.html
Files: /usr/share/doc/dspdfviewer/html/*.html
