#!/bin/bash

# Print commands as executed and fail on error
set -ex
if [ "$BUILDSYSTEM" = "outside" ] ; then
	# Test non-git non-debian build system
	TEMPDIR=$(mktemp -d)
	git archive HEAD | tar -C "$TEMPDIR" -xv
	mkdir "$TEMPDIR/build"
	cd "$TEMPDIR/build"
else
	# Test inside-git build system
	mkdir build
	cd build
fi

CMAKE_PARAMETERS="-DDownloadTestPDF=ON"

if [ "$BOOST_STATIC" ] ; then
	CMAKE_PARAMETERS="$CMAKE_PARAMETERS -DLinkBoostTestDynamic=OFF"
fi

# In any case, we're in $SOURCE/build now.
# Activate coverage iff compiling with linux/g++
if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ] ; then
	# Linux / GCC: Activate coverage
	CMAKE_PARAMETERS="$CMAKE_PARAMETERS -DCodeCoverage=ON"
fi

if [ "$QT_VERSION" -eq 4 ] ; then
	CMAKE_PARAMETERS="$CMAKE_PARAMETERS -DUseQtFive=OFF"
elif [ "$QT_VERSION" -eq 5 ] ; then
	CMAKE_PARAMETERS="$CMAKE_PARAMETERS -DUseQtFive=ON"
else
	echo "Unknown qt version $QT_VERSION" >&2
	false
fi

cmake $CMAKE_PARAMETERS ..

make VERBOSE=1
