#!/bin/bash

# Print commands as executed and fail on error
set -ex
if [ "$BUILDSYSTEM" = "outside" ] ; then
	# Test non-git non-debian build system
	TEMPDIR=$(mktemp -d)
	git archive HEAD | tar -C "$TEMPDIR" -xv
	mkdir "$TEMPDIR/build"
	cd "$TEMPDIR/build"
else
	# Test inside-git build system
	mkdir build
	cd build
fi
# In any case, we're in $SOURCE/build now.
cmake "$CMAKE_PARAMETERS" ..
make VERBOSE=1
[ -x ./dspdfviewer ]
# Activate these later:
#make test
#ctest -T coverage
