#!/bin/bash

# Exit in case of an error, and show the steps
set -ex

which ccache || brew install ccache

brew ls -v ccache

which clang++

exit 1

if [ "$QT_VERSION" -eq 5 ] ; then
	brew install poppler --with-qt5
else
	brew install poppler --with-qt
fi
