#!/bin/bash

# Exit in case of an error, and show the steps
set -ex

brew install ccache

export PATH="/usr/local/opt/ccache/libexec:$PATH"

if [ "$QT_VERSION" -eq 5 ] ; then
	brew install poppler --with-qt5
else
	brew install poppler --with-qt
fi
