#!/bin/bash

# Exit in case of an error, and show the steps
set -ex

# Travis recommends to run homebrew update
brew update > /dev/null
if [ "$QT_VERSION" -eq 5 ] ; then
	brew install poppler --with-qt5
else
	brew install poppler --with-qt
fi
