name: osx

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: 0 #FIXME:  brew is already on Qt6
    strategy:
      matrix:
        #os: [ macos-latest, macos-10.15 ]
        #buildtype: [ Debug, Release ]
        os: [ macos-10.15 ]
        buildtype: [ Debug ]
    steps:
      - uses: actions/checkout@v2
      - run: brew install boost
      - run: brew install poppler
      - name: create build/ dir
        run: >
          cmake -B build/
          -DCMAKE_VERBOSE_MAKEFILE=ON
          -DUsePrerenderedPDF=ON
          -DCodeCoverage=ON
          -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
          .
      - run: cmake --build build/
      - run: ctest --output-on-failure --timeout 60
        working-directory: build/
