name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ ubuntu-latest, ubuntu-18.04 ]
          buildtype: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - name: Install build deps
        run: >
            sudo apt-get install -y
            libboost-program-options-dev
            libboost-test-dev
            libpoppler-qt5-dev
            qtbase5-dev
            qttools5-dev
            qttools5-dev-tools
      - name: create build/ dir
        run: >
          cmake -B build/
          -DCMAKE_VERBOSE_MAKEFILE=ON
          -DUsePrerenderedPDF=ON
          -DCodeCoverage=ON
          -DUseQtFive=ON
          -DCMAKE_BUILD_TYPE=${{matrix.buildtype}}
          .
      - run: cmake --build build/
      - name: run tests within xvfb
        working-directory: build/
        run: >
            xvfb-run -a -s '-screen 0 1920x1080x24 -screen 1 1920x1200x24'
            ctest --output-on-failure --timeout 60
